### What will be outputted from the method invocation `block_method('turtle')` below? Why does/doesn't it raise an error?

```ruby
def block_method(animal)
  yield(animal)
end

block_method('turtle') do |turtle, seal|
  puts "This is a #{turtle} and a #{seal}."
end
```

The method invocation of `block_method` on lines 8-10 will output the message `This is a turtle and a .` to the console. 

There will not be an error thrown because blocks have a *lenient arity*. Arity describes the number of arguments required. Having a *lenient* arity means that Ruby will not throw an error if the wrong number of arguments is passed in.

You might suspect that line 9 will throw an error because we are referencing a second argument that was never passed in (we only pass in one argument to our `yield` on line 5). However, Ruby simply assigns this missing value to `nil` and continues to run the code with `seal` assigned to `nil` which is why we see a missing piece in our output.

